site:
  title: Gosaaan's Recipe
  url: https://gosaaan1.github.io
  start_page: local-project::index.adoc
antora:
  extensions:
    - require: ./lib/rippo-extension.js
content:
  sources:
    - url: .
      branches: HEAD
    - url: ../rippo-stories
      branches: HEAD
      start_path: .
ui:
  bundle:
    url: https://github.com/gosaaan1/rippo-ui-bundle/releases/download/latest/ui-bundle.zip
    snapshot: true
